### ISSUE TITLE
RequiredID

### ISSUE THREAD

**Issue by chandachewe10** [creagia/laravel-sign-pad#32]
So the controller class for signature contains the following validation : ` 
$validatedData = $this->validate($request, [
            'model' => ['required'],
            'sign' => ['required'],
            'id' => ['required'],
            'token' => ['required'],
        ]);` 

Which `id` are we validating since the incoming request does not contain the `id` data. I tried `dd` for the incoming request and only the `token,model, and sign` are available. As such my validation failed and I was brought to the previous page after submitting. Am I missing something?

**Comment by dtorras** [comment]
You should use the form as defined in the readme:

```
@if (!$myModel->hasBeenSigned())
    <form action="{{ $myModel->getSignatureRoute() }}" method="POST">
        @csrf
        <div style="text-align: center">
            <x-creagia-signature-pad />
        </div>
    </form>
    <script src="{{ asset('vendor/sign-pad/sign-pad.min.js') }}"></script>
@endif
```
> (from https://github.com/creagia/laravel-sign-pad/blob/main/README.md#usage)

Id and other parameters are set automatically in the `getSignatureRoute` method: https://github.com/creagia/laravel-sign-pad/blob/b9a026336a1e1e10c58aa28e5127b299e754a2b7/src/Concerns/RequiresSignature.php#L18

**Comment by chandachewe10** [comment]
Ok makes sense. my mistake thanks
